<div class="register">
    <h2>Registrace</h2>
    <form action="" method="POST">
        <div>
            <input type="email" name="email" maxlength="100" value="" required placeholder="Email">
            <input type="password" name="password" maxlength="20" value="" required placeholder="Heslo">
            <input type="password" name="password2" maxlength="20" value="" required placeholder="Ověření hesla">
            <input type="submit" name="submit" value="Registrovat do soutěže">
        </div>
        <input type="hidden" name="code" value="{code}">
        <input type="hidden" name="a" value="register">
    </form>
    <p>Email slouží pro přihlášení a prostředek pro komunikaci v případě výhry.</p>
</div>