<div class="sign">
    <h2>Přihlášení</h2>
    <form action="" method="POST">
        <div>
            <input type="email" name="email" maxlength="100" value="" required placeholder="Email">
            <input type="password" name="password" maxlength="20" value="" required placeholder="Heslo">
            <input type="submit" name="submit" value="Přihlásit">
        </div>
        <input type="hidden" name="code" value="{code}">
        <input type="hidden" name="a" value="login">
    </form>
</div>